# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

darkmode: true

# Personal info
name: Buse CANATA
title: Senior Computer Engineering Student
email: busecanata@gmail.com
website: busecanata.com.tr

# Social links
#twitter_username: facespics
github_username:  busecanata
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: busecanata
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Buse and I'm a senior computer engineering student. I have studied Java, C, C++; and I'm currently learning Machine Learning and Deep Learning.
  
  I am most skilled in: <mark>Java</mark> and <mark>Android Studio</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Cycling
   - Reading

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
